name: OpenDroneID

on:
  push:
    branches:
      - develop
    tags:
      - v[0-9]+.[0-9]+.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup credentials
      run: echo "ext.credentialsKey = \"${{ secrets.BINGMAP_NATIVE_SDK_KEY }}\"" > Android/app/secrets.gradle

    - name: Build the app
      run: cd Android && ./gradlew assembleDebug

    - name: Upload Debug APK
      if: success() && ${{ github.event_name }} != 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: opendroneid.apk
        path: Android/app/build/outputs/apk/debug/app-debug.apk
