name: Build and Deploy OpenDroneID APK

on:
  releases:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Setup credentials
      run: echo "ext.credentialsKey = \"${{ secrets.BINGMAP_NATIVE_SDK_KEY }}\"" > Android/app/secrets.gradle
    - name: Build the app
      run: cd Android && ./gradlew assembleDebug
    - name: Generate
      run: cp Android/app/build/outputs/apk/debug/app-debug.apk opendroneid.apk
    - name: Upload Debug APK
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'opendroneid.apk'
        path: Android/app/build/outputs/apk/debug/app-debug.apk
